<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ja_JP">
<context><name>Main</name>
<message><source>Main Games (PC-98)</source><translation>本編(PC-98)</translation></message><message><source>Main Games (Windows)</source><translation>本編(Windows)</translation></message>
<message><source>Official Games</source><translation>公式ゲーム</translation></message><message><source>Seihou</source><translation>西方</translation></message><message><source>Main Games</source><translation>本編ゲーム</translation></message><message><source>Spinoffs</source><translation>外伝</translation></message><message><source>Reset Settings</source><translation>設定をリセット</translation></message><message><source>Are you sure you want to reset all settings?</source><translation>すべての設定をリセットしますか？</translation></message><message><source>Close</source><translation>閉じる</translation></message><message><source>Reset</source><translation>リセット</translation></message><message><source>PC-98 Emulator Not Found!</source><translation>PC-98エミュレーターが見つかりません</translation></message><message><source>No valid PC-98 emulator was not found!&#10;Please make sure it is installed and the path is set in the binary manager.</source><translation>有効なPC-98エミュレーターが見つかりません。&#10;インストールされていることと、バイナリマネージャーでパスが設定されていることを確認してください。</translation></message><message><source>Open Binary Manager</source><translation>バイナリマネージャーを開く</translation></message>
</context>
<context><name>Footer</name>
<message><source>Reset</source><translation>リセット</translation></message>
<message><source>Warnings</source><translation>警告</translation></message><message><source>Discord RPC</source><translation>Discord RPC</translation></message><message><source>Enable Gamescope</source><translation>Gamescopeを有効化</translation></message><message><source>Launch Info</source><translation>起動情報</translation></message><message><source>Binary Manager</source><translation>バイナリマネージャー</translation></message><message><source>Japanese</source><translation>日本語</translation></message><message><source>English</source><translation>英語</translation></message><message><source>Information</source><translation>情報</translation></message><message><source>Version: </source><translation>バージョン: </translation></message><message><source>OS: </source><translation>OS: </translation></message><message><source>Qt: </source><translation>Qt: </translation></message><message><source>Arch: </source><translation>アーキテクチャ: </translation></message><message><source>Copy Info</source><translation>情報をコピー</translation></message><message><source>Info copied to clipboard!</source><translation>情報をクリップボードにコピーしました</translation></message>
</context>
<context><name>GameLaunchDialog</name>
<message><source>Launch </source><translation>起動: </translation></message><message><source>Remove Game</source><translation>ゲームを削除</translation></message><message><source>Are you sure you want to remove this game?</source><translation>このゲームを削除しますか？</translation></message><message><source>Cancel</source><translation>キャンセル</translation></message><message><source>Remove</source><translation>削除</translation></message><message><source>Launch Game</source><translation>ゲームを起動</translation></message><message><source>Launch with thprac</source><translation>thpracで起動</translation></message><message><source>Launch with thcrap</source><translation>thcrapで起動</translation></message><message><source>Configure thcrap</source><translation>thcrapを設定</translation></message><message><source>Launch Error</source><translation>起動エラー</translation></message><message><source>Please set a valid thprac.exe path in Binary Manager.</source><translation>バイナリマネージャーで有効なthprac.exeのパスを設定してください。</translation></message><message><source>Failed to start thprac.</source><translation>thpracの起動に失敗しました。</translation></message>
</context>
<context><name>GameItem</name>
<message><source>PC-98 Disk Image (*.hdi)</source><translation>PC-98ディスクイメージ (*.hdi)</translation></message><message><source>Executable (*.exe)</source><translation>実行ファイル (*.exe)</translation></message>
</context>
<context><name>BinaryManager</name>
<message><source>Binary Manager</source><translation>バイナリマネージャー</translation></message><message><source>Download thcrap</source><translation>thcrapをダウンロード</translation></message><message><source>Use System Dosbox-x</source><translation>システムのDosbox-xを使用</translation></message><message><source>Use Flatpak Dosbox-x</source><translation>FlatpakのDosbox-xを使用</translation></message><message><source>Download Dosbox-x</source><translation>Dosbox-xをダウンロード</translation></message><message><source>Use System Wine</source><translation>システムのWineを使用</translation></message><message><source>Download finished!</source><translation>ダウンロード完了</translation></message><message><source>thcrap already downloaded!</source><translation>thcrapはすでにダウンロードされています</translation></message><message><source>Dosbox-x already downloaded!</source><translation>Dosbox-xはすでにダウンロードされています</message><message><source>Proton version already downloaded! Setting to default game launcher..</source><translation>Protonはすでにダウンロードされています。既定のゲームランチャーに設定します</translation></message><message><source>thprac</source><translation>thprac</translation></message><message><source>Select thprac.exe</source><translation>thprac.exeを選択</translation></message><message><source>Clear thprac path</source><translation>thpracのパスを消去</translation></message><message><source>thprac executable (*.exe)</source><translation>thprac実行ファイル (*.exe)</translation></message><message><source>thprac path cleared.</source><translation>thpracのパスを消去しました。</translation></message><message><source>thprac path saved.</source><translation>thpracのパスを保存しました。</translation></message>
</context>
<context><name>ThcrapConfigDialog</name>
<message><source>Configure thcrap -</source><translation>thcrapを設定 -</translation></message><message><source>Downloaded repository successfully</source><translation>リポジトリのダウンロードに成功しました</translation></message><message><source>Main repository downloaded, discovering patches...</source><translation>メインリポジトリをダウンロードしました。パッチを検索しています...</translation></message><message><source>Download failed: </source><translation>ダウンロードに失敗しました: </translation></message><message><source>Discovering patches...</source><translation>パッチを検索しています...</translation></message><message><source>Repository not found. Please download patches first.</source><translation>リポジトリが見つかりません。先にパッチをダウンロードしてください。</translation></message><message><source>Found %1 patches</source><translation>%1個のパッチが見つかりました</translation></message><message><source>Failed to parse repository: </source><translation>リポジトリの解析に失敗しました: </translation></message><message><source>Found %1 patches from %2 repositories</source><translation>%2個のリポジトリから%1個のパッチが見つかりました</translation></message><message><source>Processing neighbor %1/%2: %3</source><translation>隣接リポジトリを処理中 %1/%2: %3</translation></message><message><source>Downloading thpatch repository...</source><translation>thpatchリポジトリをダウンロードしています...</translation></message><message><source>Ready</source><translation>準備完了</translation></message><message><source>Download Patches</source><translation>パッチをダウンロード</translation></message><message><source>Refresh</source><translation>更新</translation></message><message><source>Available Patches:</source><translation>利用可能なパッチ:</translation></message><message><source>Search patches...</source><translation>パッチを検索...</translation></message><message><source>Selected patches: </source><translation>選択中のパッチ: </translation></message><message><source>Deselect All</source><translation>すべて選択解除</translation></message><message><source>Configure Patch Order</source><translation>パッチの順序を設定</translation></message><message><source>Close</source><translation>閉じる</translation></message>
</context>
<context><name>ThcrapPatchOrderDialog</name>
<message><source>Configure Patch Order -</source><translation>パッチの順序を設定 -</translation></message><message><source>Reorder patches (dependencies should come first)</source><translation>パッチの順序を変更（依存パッチを先にしてください）</translation></message><message><source>Total patches: </source><translation>パッチ合計: </translation></message><message><source>Downloading patch files... (%1 remaining)</source><translation>パッチファイルをダウンロード中...（残り%1）</translation></message><message><source>Save Configuration</source><translation>設定を保存</translation></message><message><source>Cancel</source><translation>キャンセル</translation></message>
</context>
</TS>