<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context><name>Main</name>
<message><source>Official Games</source><translation>Official Games</translation></message>
<message><source>Seihou</source><translation>Seihou</translation></message>
<message><source>Main Games</source><translation>Main Games</translation></message>
<message><source>Main Games (PC-98)</source><translation>Main Games (PC-98)</translation></message>
<message><source>Main Games (Windows)</source><translation>Main Games (Windows)</translation></message>
<message><source>Spinoffs</source><translation>Spinoffs</translation></message>
<message><source>Reset Settings</source><translation>Reset Settings</translation></message>
<message><source>Are you sure you want to reset all settings?</source><translation>Are you sure you want to reset all settings?</translation></message>
<message><source>Close</source><translation>Close</translation></message>
<message><source>Reset</source><translation>Reset</translation></message>
<message><source>PC-98 Emulator Not Found!</source><translation>PC-98 Emulator Not Found!</translation></message>
<message><source>No valid PC-98 emulator was not found!&#10;Please make sure it is installed and the path is set in the binary manager.</source><translation>No valid PC-98 emulator was not found!&#10;Please make sure it is installed and the path is set in the binary manager.</translation></message>
<message><source>Open Binary Manager</source><translation>Open Binary Manager</translation></message>
</context>
<context><name>Footer</name>
<message><source>Reset</source><translation>Reset</translation></message>
<message><source>Warnings</source><translation>Warnings</translation></message><message><source>Discord RPC</source><translation>Discord RPC</translation></message><message><source>Enable Gamescope</source><translation>Enable Gamescope</translation></message><message><source>Launch Info</source><translation>Launch Info</translation></message><message><source>Binary Manager</source><translation>Binary Manager</translation></message><message><source>Japanese</source><translation>Japanese</translation></message><message><source>English</source><translation>English</translation></message><message><source>Information</source><translation>Information</translation></message><message><source>Version: </source><translation>Version: </translation></message><message><source>OS: </source><translation>OS: </translation></message><message><source>Qt: </source><translation>Qt: </translation></message><message><source>Arch: </source><translation>Arch: </translation></message><message><source>Copy Info</source><translation>Copy Info</translation></message><message><source>Info copied to clipboard!</source><translation>Info copied to clipboard!</translation></message>
</context>
<context><name>GameLaunchDialog</name>
<message><source>Launch </source><translation>Launch </translation></message><message><source>Remove Game</source><translation>Remove Game</translation></message><message><source>Are you sure you want to remove this game?</source><translation>Are you sure you want to remove this game?</translation></message><message><source>Cancel</source><translation>Cancel</translation></message><message><source>Remove</source><translation>Remove</translation></message><message><source>Launch Game</source><translation>Launch Game</translation></message><message><source>Launch with thcrap</source><translation>Launch with thcrap</translation></message><message><source>Configure thcrap</source><translation>Configure thcrap</translation></message>
</context>
<context><name>GameItem</name>
<message><source>PC-98 Disk Image (*.hdi)</source><translation>PC-98 Disk Image (*.hdi)</translation></message><message><source>Executable (*.exe)</source><translation>Executable (*.exe)</translation></message>
</context>
<context><name>BinaryManager</name>
<message><source>Binary Manager</source><translation>Binary Manager</translation></message><message><source>Download thcrap</source><translation>Download thcrap</translation></message><message><source>Use System Dosbox-x</source><translation>Use System Dosbox-x</translation></message><message><source>Use Flatpak Dosbox-x</source><translation>Use Flatpak Dosbox-x</translation></message><message><source>Download Dosbox-x</source><translation>Download Dosbox-x</translation></message><message><source>Use System Wine</source><translation>Use System Wine</translation></message><message><source>Download finished!</source><translation>Download finished!</translation></message><message><source>thcrap already downloaded!</source><translation>thcrap already downloaded!</translation></message><message><source>Dosbox-x already downloaded!</source><translation>Dosbox-x already downloaded!</translation></message><message><source>Proton version already downloaded! Setting to default game launcher..</source><translation>Proton version already downloaded! Setting to default game launcher..</translation></message>
</context>
<context><name>ThcrapConfigDialog</name>
<message><source>Configure thcrap -</source><translation>Configure thcrap -</translation></message><message><source>Downloaded repository successfully</source><translation>Downloaded repository successfully</translation></message><message><source>Main repository downloaded, discovering patches...</source><translation>Main repository downloaded, discovering patches...</translation></message><message><source>Download failed: </source><translation>Download failed: </translation></message><message><source>Discovering patches...</source><translation>Discovering patches...</translation></message><message><source>Repository not found. Please download patches first.</source><translation>Repository not found. Please download patches first.</translation></message><message><source>Found %1 patches</source><translation>Found %1 patches</translation></message><message><source>Failed to parse repository: </source><translation>Failed to parse repository: </translation></message><message><source>Found %1 patches from %2 repositories</source><translation>Found %1 patches from %2 repositories</translation></message><message><source>Processing neighbor %1/%2: %3</source><translation>Processing neighbor %1/%2: %3</translation></message><message><source>Downloading thpatch repository...</source><translation>Downloading thpatch repository...</translation></message><message><source>Ready</source><translation>Ready</translation></message><message><source>Download Patches</source><translation>Download Patches</translation></message><message><source>Refresh</source><translation>Refresh</translation></message><message><source>Available Patches:</source><translation>Available Patches:</translation></message><message><source>Search patches...</source><translation>Search patches...</translation></message><message><source>Selected patches: </source><translation>Selected patches: </translation></message><message><source>Deselect All</source><translation>Deselect All</translation></message><message><source>Configure Patch Order</source><translation>Configure Patch Order</translation></message><message><source>Close</source><translation>Close</translation></message>
</context>
<context><name>ThcrapPatchOrderDialog</name>
<message><source>Configure Patch Order -</source><translation>Configure Patch Order -</translation></message><message><source>Reorder patches (dependencies should come first)</source><translation>Reorder patches (dependencies should come first)</translation></message><message><source>Total patches: </source><translation>Total patches: </translation></message><message><source>Downloading patch files... (%1 remaining)</source><translation>Downloading patch files... (%1 remaining)</translation></message><message><source>Save Configuration</source><translation>Save Configuration</translation></message><message><source>Cancel</source><translation>Cancel</translation></message>
</context>
</TS>